'strategy':
    currency: BTC
    contractSize: 0.1
    compounding: False
    targetDelta: 0.15
    optionSides: ['put', 'call']
    optionSettlement: day
    hedging: False
    hedgingThreshold: 0.06
    rolling: True
    rollingTargetProfit: 0.8
    orderType: maker
'deribit':
    key: xxx
    secret: xxx
'notification':
    telegramChatId: xxx
    alias: Main